---
# Source: jamadar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.6
    chart: "jamadar-0.0.6"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar
data:
  config.yaml: |-
    polltimeinterval: 20m
    age: 7d
    actions:
      - name: slack
        params:
          channel: <channel-name>
          token: <token>    
