---
# Source: jamadar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.13
    chart: "jamadar-0.0.13"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar
data:
  config.yaml: |-
    pollTimeInterval: 20m
    age: 7d
    resources:
      - namespaces
    actions:
      - name: slack
        params:
          channel: <channel-name>
          token: <token>    
    restrictedNamespaces:
      - kube-system
      - default
      - kube-public

