---
# Source: jamadar/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: jamadar
  labels:
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: v0.0.14
    chart: "jamadar-v0.0.14"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jamadar
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: jamadar
      labels:
        app: jamadar
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/jamadar:v0.0.14"
        imagePullPolicy: IfNotPresent
        name: jamadar
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: jamadar
      volumes:
      - configMap:
          name: jamadar
        name: config-volume
              
