---
# Source: jamadar/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.8
    chart: "jamadar-0.0.8"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels: 
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.8
    chart: "jamadar-0.0.8"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar-role
rules:
  - apiGroups:
      - ""
    resources:      
      - namespaces
    verbs:
      - list
      - get
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels: 
    app: jamadar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.8
    chart: "jamadar-0.0.8"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: jamadar-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jamadar-role
subjects:
  - kind: ServiceAccount
    name: jamadar
    namespace: .Release.Namespace
