apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
data:
  config.yaml: |-
    polltimeinterval: {{ .Values.jamadar.polltimeinterval }}
    age: {{ .Values.jamadar.age }}
    actions:
      {{- range .Values.jamadar.actions }}
      - name: {{ .name }}
        params:
        {{- range $key, $value := .params }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}    