pollTimeInterval: 12h     # Values: "ms", "s", "m", "h".
age: 1m                  # Values: "d" or "w" or "m" or "y".
resources:
  - namespaces
actions:
  - name: default
  - name: slack
    params:
      token: <token>
      channel: <channel-name>
restrictedNamespaces: 
  - kube-system
  - default
  - kube-public
  - dev
  - prod
  - tools